[package]
org = "ballerinax"
name = "financial.iso8583"
version = "0.1.0"
authors=["Ballerina"]
keywords=["Financial", "iso8583", "v87"]
distribution = "2201.10.0"
repository="https://github.com/ballerina-platform/module-ballerinax-financial.iso8583"
visibility="private"

[[platform.java17.dependency]]
groupId = "io.ballerinax"
artifactId = "iso8583"
version = "0.1.0-SNAPSHOT"

# transitive dependency of io.ballerinax:iso8583:0.1.0-SNAPSHOT
[[platform.java17.dependency]]
groupId = "org.jpos"
artifactId = "jpos"
version = "2.1.9"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "org.jdom"
artifactId = "jdom2"
version = "2.0.6.1"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "org.javatuples"
artifactId = "javatuples"
version = "1.2"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "org.jline"
artifactId = "jline"
version = "3.23.0"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "org.apache-extras.beanshell"
artifactId = "bsh"
version = "2.0b6"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "commons-cli"
artifactId = "commons-cli"
version = "1.4"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcprov-lts8on"
version = "2.73.2"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcpg-lts8on"
version = "2.73.2"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "org.osgi"
artifactId = "org.osgi.core"
version = "6.0.0"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "org.yaml"
artifactId = "snakeyaml"
version = "2.0"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "jdbm"
artifactId = "jdbm"
version = "1.0"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "com.sleepycat"
artifactId = "je"
version = "18.3.12"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "org.apache.sshd"
artifactId = "sshd-core"
version = "2.9.2"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "org.apache.sshd"
artifactId = "sshd-common"
version = "2.9.2"

# transitive dependency of org.jpos:jpos:2.1.9
[[platform.java17.dependency]]
groupId = "net.i2p.crypto"
artifactId = "eddsa"
version = "0.3.0"

# transitive dependency of io.ballerinax:iso8583:0.1.0-SNAPSHOT
[[platform.java17.dependency]]
groupId = "org.json.wso2"
artifactId = "json"
version = "3.0.0.wso2v4"
